# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trap_scorekeeping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='handicap',
            field=models.IntegerField(default=16),
        ),
    ]
