# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trap_scorekeeping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shells',
            name='gauge',
        ),
        migrations.AlterField(
            model_name='round',
            name='singles_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='singles_score', to='trap_scorekeeping.SinglesScore'),
        ),
        migrations.AlterField(
            model_name='shotgun',
            name='gauge',
            field=models.CharField(choices=[('12', '12 Gauge'), ('20', '20 Gauge'), ('28', '28 Gauge'), ('410', '410 Gauge')], default='12', max_length=255),
        ),
        migrations.DeleteModel(
            name='Gauge',
        ),
    ]
