# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 17:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trap_scorekeeping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShotAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shot_amount', models.CharField(choices=[('7/8', '7/8oz'), ('1', '1oz'), ('1 1/8', '1 1/8oz')], default='1', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ShotSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shot', models.CharField(choices=[('7.5', '7.5 Shot'), ('8', '8 Shot'), ('8.5', '8.5'), ('9', '9')], default='7.5', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StartingStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.CharField(choices=[('1', 'Station 1'), ('2', 'Station 2'), ('3', 'Station 3'), ('4', 'Station 4'), ('5', 'Station 5')], default='1', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='shells',
            name='dram_equivalent',
        ),
        migrations.AddField(
            model_name='round',
            name='player',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='round',
            name='singles_round',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='trap_scorekeeping.SinglesScore'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='singlesscore',
            name='score',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='gauge',
            name='gauge',
            field=models.CharField(choices=[('12', '12 Gauge'), ('20', '20 Gauge'), ('28', '28 Gauge'), ('410', '410 Gauge')], default='12', max_length=255),
        ),
        migrations.AlterField(
            model_name='shells',
            name='brand',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='shells',
            name='fps_rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shells',
            name='shot_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size', to='trap_scorekeeping.ShotSize'),
        ),
        migrations.AlterField(
            model_name='shells',
            name='shot_weight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight', to='trap_scorekeeping.ShotAmount'),
        ),
        migrations.AlterField(
            model_name='shells',
            name='sku',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='shotgun',
            name='barrel_length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shotgun',
            name='brand',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='shotgun',
            name='model',
            field=models.CharField(max_length=25),
        ),
        migrations.AddField(
            model_name='round',
            name='starting_station',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='first_station', to='trap_scorekeeping.ShotSize'),
            preserve_default=False,
        ),
    ]
