# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trap_scorekeeping', '0002_auto_20160909_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shells',
            name='shot_size',
        ),
        migrations.RemoveField(
            model_name='shells',
            name='shot_weight',
        ),
        migrations.AddField(
            model_name='shells',
            name='shot',
            field=models.CharField(choices=[('7.5', '7.5 Shot'), ('8', '8 Shot'), ('8.5', '8.5'), ('9', '9')], default='7.5', max_length=255),
        ),
        migrations.AddField(
            model_name='shells',
            name='shot_amount',
            field=models.CharField(choices=[('7/8', '7/8oz'), ('1', '1oz'), ('1 1/8', '1 1/8oz')], default='1', max_length=255),
        ),
        migrations.DeleteModel(
            name='ShotAmount',
        ),
        migrations.DeleteModel(
            name='ShotSize',
        ),
    ]
