# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trap_scorekeeping', '0002_auto_20160908_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gauge',
            name='gauge',
            field=models.CharField(choices=[('12', '12 Gauge'), ('20', '20 Gauge'), ('28', '28 Gauge'), ('410', '410 Gauge')], default='12', max_length=1),
        ),
    ]
