# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trap_scorekeeping', '0003_auto_20160909_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='excuses',
            field=models.TextField(default=''),
        ),
    ]
