# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trap_scorekeeping', '0005_auto_20160908_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='singles_round',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trap_scorekeeping.SinglesScore'),
        ),
        migrations.AlterField(
            model_name='singlesscore',
            name='score',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
