# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trap_scorekeeping', '0008_auto_20160908_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shotamount',
            name='shot_amount',
            field=models.CharField(choices=[('7/8', '7/8oz'), ('1', '1oz'), ('1 1/8', '1 1/8oz')], default='1', max_length=255),
        ),
    ]
